server:
  port: 8181

spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:walletdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    # schema.sql script will execute after the entity tables have been created
    defer-datasource-initialization: true

logging:
  pattern:
    console: "%d %-5level %logger:%L : %msg%n"
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE